services:
  app:
    env_file:
      - container.env
    image: localbuild/curriculum-vitae
    container_name: dev-curriculum-vitae
    pull_policy: build
    build:
      context: ./
      dockerfile: src/main/docker/Dockerfile.jvm
      # dockerfile: src/main/docker/full-build-jvm.Dockerfile
    volumes:
      - ./volume/moved_root/deployments/storage:/deployments/storage
      - ./volume/moved_root/deployments/config:/deployments/config
    post_start:
      - command: "chown 185:root /deployments/storage"
        user: root
    network_mode: bridge
    ports:
      - "8880:8880"
    restart: unless-stopped
