/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/cv-root-page': RouteRecordInfo<
      '/cv-root-page',
      '/cv-root-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/first-time-loading-page': RouteRecordInfo<
      '/first-time-loading-page',
      '/first-time-loading-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/hr-info-page': RouteRecordInfo<
      '/hr-info-page',
      '/hr-info-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login-page': RouteRecordInfo<
      '/login-page',
      '/login-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/not-found-page': RouteRecordInfo<
      '/not-found-page',
      '/not-found-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/routes': RouteRecordInfo<
      '/routes',
      '/routes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/setting-page': RouteRecordInfo<
      '/setting-page',
      '/setting-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/study-blob-url': RouteRecordInfo<
      '/study-blob-url',
      '/study-blob-url',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test-chatgpt-works': RouteRecordInfo<
      '/test-chatgpt-works',
      '/test-chatgpt-works',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test-community-box': RouteRecordInfo<
      '/test-community-box',
      '/test-community-box',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test-font-support': RouteRecordInfo<
      '/test-font-support',
      '/test-font-support',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test-hr-info-page': RouteRecordInfo<
      '/test-hr-info-page',
      '/test-hr-info-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test-page': RouteRecordInfo<
      '/test-page',
      '/test-page',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test-resize-observer': RouteRecordInfo<
      '/test-resize-observer',
      '/test-resize-observer',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test-tianai-captcha': RouteRecordInfo<
      '/test-tianai-captcha',
      '/test-tianai-captcha',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test-vxe-table-paged': RouteRecordInfo<
      '/test-vxe-table-paged',
      '/test-vxe-table-paged',
      Record<never, never>,
      Record<never, never>,
      | '/test-vxe-table-paged/'
      | '/test-vxe-table-paged/infinite-plain'
      | '/test-vxe-table-paged/infinite-window'
    >,
    '/test-vxe-table-paged/': RouteRecordInfo<
      '/test-vxe-table-paged/',
      '/test-vxe-table-paged',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test-vxe-table-paged/infinite-plain': RouteRecordInfo<
      '/test-vxe-table-paged/infinite-plain',
      '/test-vxe-table-paged/infinite-plain',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/test-vxe-table-paged/infinite-window': RouteRecordInfo<
      '/test-vxe-table-paged/infinite-window',
      '/test-vxe-table-paged/infinite-window',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/cv-root-page.vue': {
      routes:
        | '/cv-root-page'
      views:
        | never
    }
    'src/pages/first-time-loading-page.vue': {
      routes:
        | '/first-time-loading-page'
      views:
        | never
    }
    'src/pages/hr-info-page.vue': {
      routes:
        | '/hr-info-page'
      views:
        | never
    }
    'src/pages/login-page.vue': {
      routes:
        | '/login-page'
      views:
        | never
    }
    'src/pages/not-found-page.vue': {
      routes:
        | '/not-found-page'
      views:
        | never
    }
    'src/pages/routes.vue': {
      routes:
        | '/routes'
      views:
        | never
    }
    'src/pages/setting-page.vue': {
      routes:
        | '/setting-page'
      views:
        | never
    }
    'src/pages/study-blob-url.vue': {
      routes:
        | '/study-blob-url'
      views:
        | never
    }
    'src/pages/test-chatgpt-works.vue': {
      routes:
        | '/test-chatgpt-works'
      views:
        | never
    }
    'src/pages/test-community-box.vue': {
      routes:
        | '/test-community-box'
      views:
        | never
    }
    'src/pages/test-font-support.vue': {
      routes:
        | '/test-font-support'
      views:
        | never
    }
    'src/pages/test-hr-info-page.vue': {
      routes:
        | '/test-hr-info-page'
      views:
        | never
    }
    'src/pages/test-page.vue': {
      routes:
        | '/test-page'
      views:
        | never
    }
    'src/pages/test-resize-observer.vue': {
      routes:
        | '/test-resize-observer'
      views:
        | never
    }
    'src/pages/test-tianai-captcha.vue': {
      routes:
        | '/test-tianai-captcha'
      views:
        | never
    }
    'src/pages/test-vxe-table-paged.vue': {
      routes:
        | '/test-vxe-table-paged'
        | '/test-vxe-table-paged/'
        | '/test-vxe-table-paged/infinite-plain'
        | '/test-vxe-table-paged/infinite-window'
      views:
        | 'default'
    }
    'src/pages/test-vxe-table-paged/index.vue': {
      routes:
        | '/test-vxe-table-paged/'
      views:
        | never
    }
    'src/pages/test-vxe-table-paged/infinite-plain.vue': {
      routes:
        | '/test-vxe-table-paged/infinite-plain'
      views:
        | never
    }
    'src/pages/test-vxe-table-paged/infinite-window.vue': {
      routes:
        | '/test-vxe-table-paged/infinite-window'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
